name: crud_app
description: Uma aplicação Flutter para CRUD de Clientes e Produtos.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.5
  email_validator: ^2.0.1

  flutter_staggered_animations: ^1.0.0
  cached_network_image: ^3.2.1


flutter:
  uses-material-design: true


dev_dependencies:
  flutter_test:
    sdk: flutter
